### ISSUE TITLE
update is not statically linked

### ISSUE THREAD

**Issue by a16bitsysop** [SequentMicrosystems/megaind-rpi#10]
It won't run on alpine linux as it is dynamically linked to glibc, I tried alpine glibc compatibility library but I am running aarch64 as well.

**Comment by alexburcea2877** [comment]
We plan to test on alpine linux but unfortunately we have no chance to do it in the next month.
Thank you for your understanding.

**Comment by a16bitsysop** [comment]
I have added a node-red example now to the project, it is now raspi-alpine/builder
https://gitlab.com/raspi-alpine/builder/-/tree/master/examples/node-red

It clones this repo and builds app and python image, and installs node-red modules with yarn.

I think if you statically link the update app like this:
https://gitlab.com/raspi-alpine/builder/-/blob/master/Dockerfile#L61 

It should work, the uboot tool is compiled in Debian which is glibc and runs on alpine which is musl.
