### ISSUE TITLE
How to use megaind module in C program

### ISSUE THREAD

**Issue by Controlnetix** [SequentMicrosystems/megaind-rpi#13]
Hello, Alex

Would you please suggest how to use Industrial HAT module in C?
Are there any sample program to read/write digital and analog IOs in C?

Thanks
Nilesh Suthar

**Comment by alexburcea2877** [comment]
Hi,
Unfortunately we have no usage example in C but our command line interface is entirely write in C and the source code is available in this repo, checkout the src folder: https://github.com/SequentMicrosystems/megaind-rpi/tree/master/src
If you have questions about source code feel free to ask.

Alex.
