### ISSUE TITLE
I2C Command frequency

### ISSUE THREAD

**Issue by vtx22** [SequentMicrosystems/megaind-rpi#16]
Hello,

I've written a C++ application that controls the Industrial Automation Board via I2C. Sending the commands manually works fine so far, however I've noticed some glitches when sending fast consecutive commands. Introducing a delay between the commands fixed the problems somewhat. The delay came out to be about 8 - 10ms through experimentation. Is that observation about right or is the fastest possible I2C command frequency higher? Because 10ms delay sounds quiet high in my opinion.

Regards

**Comment by alexburcea2877** [comment]
Hi,
Let me know the firmware version of your card (run the "megaind 0 board" command in the terminal)

**Comment by vtx22** [comment]
Hi,
the firmware version is 01.10

**Comment by alexburcea2877** [comment]
Please update to the latest, instructions: https://github.com/SequentMicrosystems/megaind-rpi/blob/master/update/README.md
Let me know if something change.

**Comment by vtx22** [comment]
Thanks, that decreased the minimum time to about 1ms, which is fast enough for my application. However, i've noticed some odd glitches. As a test, i wrote a program that toggles the four on board LEDs every second by sending the four I2C commands consecutively with 1ms delay (as you can see in the picture)

![Screenshot 2022-05-05 204045](https://user-images.githubusercontent.com/58121786/166999420-ca8f9392-dba0-420f-9b83-7d950200817e.png)

In about 95% of the time everything goes right, but sometimes one LEDs does not toggle. The same behaviour occurs when changing the delay to 2ms, as if the IABoard is sometimes busy and cannot react on the command. Is there a way to work around that issue (instead of increasing the delay again) or should i just double ckeck with a read command if the right value was set?

**Comment by alexburcea2877** [comment]
The i2c bus respond faster than millisecond but the loop that check if a new LED command has arrived repeat every millisecond (inside the microcontroller on the card).
Try to use the 2ms delay, that should be enough for the LED command to be executed.

**Comment by vtx22** [comment]
I see, thanks for your help
