### ISSUE TITLE
install uses `chown root.root` instead of `chown root:root`

### ISSUE THREAD

**Issue by a16bitsysop** [SequentMicrosystems/megaind-rpi#18]
https://github.com/SequentMicrosystems/megaind-rpi/blob/870731343ecac88c825bbb376f2b39a40fc9b595/Makefile#L38

The man page does not list this syntax
https://linux.die.net/man/1/chown

**Comment by alexburcea2877** [comment]
The syntax has been fixed. Thank you again.
Alex.
