### ISSUE TITLE
error in tell the local processor to release control of the RS485 bus:

### ISSUE THREAD

**Issue by kang2k10** [SequentMicrosystems/megaind-rpi#19]
After send command> megaind 0 rs485wr 0 0 0 0 0
return error: Invalid RS485 Baudrate [1200, 920600]!

firmware 02.02

**Comment by alexburcea2877** [comment]
Hi,
Even if the first parameter is 0 the rest of them does not matter I still check all the parameters (bug, I will solve it in the next version)
Try  megaind 0 rs485wr 0 9600 1 0 1

**Comment by kang2k10** [comment]
Hi.
megaind 0 rs485wr 0 9600 1 0 1
without error. Thanks
