### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by AMcCutceon** [SequentMicrosystems/megaind-rpi#22]
Hi

clone the git repository, then run sudo make install, i get several errors:

[Compile] src/megaind.c
src/megaind.c: In function ‘doOwbIdGet’:
src/megaind.c:475:15: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  475 |  printf("0x%llx\n", romID);
      |            ~~~^     ~~~~~
      |               |     |
      |               |     uint64_t {aka long unsigned int}
      |               long long unsigned int
      |            %lx
[Compile] src/comm.c
[Compile] src/thread.c
[Compile] src/opto.c
[Compile] src/wdt.c
[Compile] src/rtc.c
[Compile] src/rs485.c
[Compile] src/analog.c
src/analog.c: In function ‘val16Get’:
src/analog.c:25:35: error: ‘I2C_MEM_SIZE’ undeclared (first use in this function); did you mean ‘I2C_MEM_HSI_HI’?
   25 |  if ( (baseAdd + 2 * (ch - 1)) >= I2C_MEM_SIZE)
      |                                   ^~~~~~~~~~~~
      |                                   I2C_MEM_HSI_HI
src/analog.c:25:35: note: each undeclared identifier is reported only once for each function it appears in
src/analog.c: In function ‘val16Set’:
src/analog.c:57:35: error: ‘I2C_MEM_SIZE’ undeclared (first use in this function); did you mean ‘I2C_MEM_HSI_HI’?
   57 |  if ( (baseAdd + 2 * (ch - 1)) >= I2C_MEM_SIZE)
      |                                   ^~~~~~~~~~~~
      |                                   I2C_MEM_HSI_HI
make: *** [Makefile:26: src/analog.o] Error 1

**Comment by alexburcea2877** [comment]
Forgot do make clean after last compile.
I will fix-it asap

**Comment by alexburcea2877** [comment]
Done, update the repo and install
