### ISSUE TITLE
Why can't I activate all 4 LEDs at once?

### ISSUE THREAD

**Issue by IamSierraCharlie** [SequentMicrosystems/megaind-rpi#28]
As the subject suggests.

If I do:
```
import megaind as meg
meg.setLed(0,1,1)
meg.setLed(0,2,1)
meg.setLed(0,3,1)
meg.setLed(0,4,1)
```
Only the first 3 LEDs come on.  I then disable any LED (except the 4th) and the final LED comes on.

Also, if I do 

`meg.setLedAll(0, 1)`

only the first LED comes on - not all.

I updated the firmware and power cycled the pi - no change.

**Comment by IamSierraCharlie** [comment]
FW version is 2.06 by the way

**Comment by alexburcea2877** [comment]
To update all led's you need to send a bitmap with all 4: "meg.setLedAll(0,15)" will enable all the LED's ;  "meg.setLedAll(0,5)" will turn on LED 1 and 3, and turn off led 2 and 4.

**Comment by IamSierraCharlie** [comment]
Thanks,  I'll give it a try!

**Comment by alexburcea2877** [comment]
You never answered but I am sure it works
