### ISSUE TITLE
WDT_MAX_POWER_OFF_INTERVAL not defined

### ISSUE THREAD

**Issue by gaynoraj19** [SequentMicrosystems/megaind-rpi#3]
https://github.com/SequentMicrosystems/megaind-rpi/blob/master/python/megaind/__init__.py
Line 407
```
def wdtSetOffInterval(stack, val):
    ret = 1
    hwAdd = checkStack(stack)
    if 10 > val or val > WDT_MAX_POWER_OFF_INTERVAL:
```

WDT_MAX_POWER_OFF_INTERVAL is not defined

**Comment by alexburcea2877** [comment]
Hi,

Thank you for finding the bug.
Update your repository and reinstall the library.
Let me know if is solved.

Alex

**Comment by gaynoraj19** [comment]
Will do, thank you. I will post any findings here

**Comment by alexburcea2877** [comment]
You are write, thank you. I was planning to write some unit test for checking every function but was unable to do it.

Thanks again.

**Comment by alexburcea2877** [comment]
I did the changes, let me know if is something else wrong.

**Comment by gaynoraj19** [comment]
It seems to be working correctly now, thank you
