### ISSUE TITLE
Watchdog reset node

### ISSUE THREAD

**Issue by PBnFlash** [SequentMicrosystems/megaind-rpi#30]
I understand there are no timing guarantees on a rpi but surely it would make sense to manually trigger the watchdog reset from node-red directly rather than calling an external script?

**Comment by alexburcea2877** [comment]
You can do that using exec node, running  wdt command

**Comment by PBnFlash** [comment]
I had to shut down the node red service before it would reboot, even after submitting the wdtr command from the command line. Node red doesn't send the command automatically while in development mode or something?

Is there any way to check how long it's been since the last watchdog reset?

**Comment by alexburcea2877** [comment]
I am not understand the problem but NodeRed does nothing unless you tell it to.
There is no way to find the time from last watchdog reset.

**Comment by PBnFlash** [comment]
Sorry, I was trying to trigger the watchdog and have the device reset automatically (to test the feature.) However even after starting the watchdog from the console the device would not reset with the node red service running.

Feel free to close this I'll examine my setup closer and if I can replicate I'll re-open with replication steps. 

Impressed with the hat so far lovely device.

**Comment by alexburcea2877** [comment]
You should close this when you consider is done.
Any access to the card prevents watchdog from reset the PI, it consider the RPI is not hung.

**Comment by PBnFlash** [comment]
Ah, interesting. Thank you for your help.
