### ISSUE TITLE
How use megaind-pi liberary in Docker Containre

### ISSUE THREAD

**Issue by nainesh72** [SequentMicrosystems/megaind-rpi#9]
Hi
I develop python code it works fine, but when i build the docker container  and  run the container it is missing module, megaind
please have any idea to add this library in the docker file 
How I add  megaind library to docker container 
Thanks

**Comment by alexburcea2877** [comment]
Hi,
Sorry for the late response, I did not use the docker container and have no idea how to install a new library. My guess is that I publish the library to pypi (also never do that but look doable ) will solve your problem. If this is the case let me know and I will try to publish it. 
Alex.
